.TH "_AFD_SEND_INFO" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_AFD_SEND_INFO
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPAFD_WSABUF\fP \fBBufferArray\fP"
.br
.ti -1c
.RI "ULONG \fBBufferCount\fP"
.br
.ti -1c
.RI "ULONG \fBAfdFlags\fP"
.br
.ti -1c
.RI "ULONG \fBTdiFlags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing information for sending data using AFD\&. 
.PP
Definition at line \fB459\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG _AFD_SEND_INFO::AfdFlags"

.PP
Definition at line \fB462\fP of file \fBnosa\&.h\fP\&.
.SS "\fBPAFD_WSABUF\fP _AFD_SEND_INFO::BufferArray"

.PP
Definition at line \fB460\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _AFD_SEND_INFO::BufferCount"

.PP
Definition at line \fB461\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _AFD_SEND_INFO::TdiFlags"

.PP
Definition at line \fB463\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
