.TH "_AFD_LISTEN_DATA" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_AFD_LISTEN_DATA
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BOOLEAN \fBUseSAN\fP"
.br
.ti -1c
.RI "ULONG \fBBacklog\fP"
.br
.ti -1c
.RI "BOOLEAN \fBUseDelayedAcceptance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing AFD listen data\&. 
.PP
Definition at line \fB316\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG _AFD_LISTEN_DATA::Backlog"

.PP
Definition at line \fB318\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _AFD_LISTEN_DATA::UseDelayedAcceptance"

.PP
Definition at line \fB319\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _AFD_LISTEN_DATA::UseSAN"

.PP
Definition at line \fB317\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
