.TH "_AFD_BIND_DATA" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_AFD_BIND_DATA
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ULONG \fBShareType\fP"
.br
.ti -1c
.RI "SOCKADDR_IN \fBaddr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing AFD bind data\&. 
.PP
Definition at line \fB307\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "SOCKADDR_IN _AFD_BIND_DATA::addr"

.PP
Definition at line \fB310\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _AFD_BIND_DATA::ShareType"

.PP
Definition at line \fB309\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
