.TH "_AFD_ACCEPT_DATA" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_AFD_ACCEPT_DATA
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BOOLEAN \fBUseSAN\fP"
.br
.ti -1c
.RI "ULONG \fBSequenceNumber\fP"
.br
.ti -1c
.RI "HANDLE \fBListenHandle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing data for accepting connections in the AFD (Ancillary Function Driver)\&. 
.PP
Definition at line \fB325\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "HANDLE _AFD_ACCEPT_DATA::ListenHandle"

.PP
Definition at line \fB328\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _AFD_ACCEPT_DATA::SequenceNumber"

.PP
Definition at line \fB327\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _AFD_ACCEPT_DATA::UseSAN"

.PP
Definition at line \fB326\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
