.TH "_AFD_WSABUF" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_AFD_WSABUF
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ULONG_PTR \fBlen\fP"
.br
.ti -1c
.RI "PVOID \fBbuf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing a buffer and its length for Winsock operations\&. 
.PP
Definition at line \fB427\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "PVOID _AFD_WSABUF::buf"

.PP
Definition at line \fB430\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG_PTR _AFD_WSABUF::len"

.PP
Definition at line \fB429\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
