.TH "_AFD_RECV_INFO" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_AFD_RECV_INFO
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPAFD_WSABUF\fP \fBBufferArray\fP"
.br
.ti -1c
.RI "DWORD \fBBufferCount\fP"
.br
.ti -1c
.RI "DWORD \fBAfdFlags\fP"
.br
.ti -1c
.RI "DWORD \fBTdiFlags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing information for AFD receive operation\&. 
.PP
Definition at line \fB436\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "DWORD _AFD_RECV_INFO::AfdFlags"

.PP
Definition at line \fB440\fP of file \fBnosa\&.h\fP\&.
.SS "\fBPAFD_WSABUF\fP _AFD_RECV_INFO::BufferArray"

.PP
Definition at line \fB438\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _AFD_RECV_INFO::BufferCount"

.PP
Definition at line \fB439\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _AFD_RECV_INFO::TdiFlags"

.PP
Definition at line \fB441\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
