.TH "_AFD_RECV_INFO_UDP" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_AFD_RECV_INFO_UDP
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPAFD_WSABUF\fP \fBBufferArray\fP"
.br
.ti -1c
.RI "ULONG \fBBufferCount\fP"
.br
.ti -1c
.RI "ULONG \fBAfdFlags\fP"
.br
.ti -1c
.RI "ULONG \fBTdiFlags\fP"
.br
.ti -1c
.RI "PVOID \fBAddress\fP"
.br
.ti -1c
.RI "PINT \fBAddressLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing information for UDP receive operation in AFD\&. 
.PP
Definition at line \fB447\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "PVOID _AFD_RECV_INFO_UDP::Address"

.PP
Definition at line \fB452\fP of file \fBnosa\&.h\fP\&.
.SS "PINT _AFD_RECV_INFO_UDP::AddressLength"

.PP
Definition at line \fB453\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _AFD_RECV_INFO_UDP::AfdFlags"

.PP
Definition at line \fB450\fP of file \fBnosa\&.h\fP\&.
.SS "\fBPAFD_WSABUF\fP _AFD_RECV_INFO_UDP::BufferArray"

.PP
Definition at line \fB448\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _AFD_RECV_INFO_UDP::BufferCount"

.PP
Definition at line \fB449\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _AFD_RECV_INFO_UDP::TdiFlags"

.PP
Definition at line \fB451\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
