.TH "_CLIENT_ID" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_CLIENT_ID
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "HANDLE \fBUniqueProcess\fP"
.br
.ti -1c
.RI "HANDLE \fBUniqueThread\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB230\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "HANDLE _CLIENT_ID::UniqueProcess"

.PP
Definition at line \fB232\fP of file \fBnosa\&.h\fP\&.
.SS "HANDLE _CLIENT_ID::UniqueThread"

.PP
Definition at line \fB233\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
