.TH "_DOMAIN_INFO" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_DOMAIN_INFO
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBhex_ip_address\fP"
.br
.ti -1c
.RI "unsigned char \fBip_address_str\fP [16]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing information for further DNS query lookup\&. 
.PP
Definition at line \fB486\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint32_t\fP _DOMAIN_INFO::hex_ip_address"

.PP
Definition at line \fB488\fP of file \fBnosa\&.h\fP\&.
.SS "unsigned char _DOMAIN_INFO::ip_address_str[16]"

.PP
Definition at line \fB489\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
