.TH "_INITIAL_TEB" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_INITIAL_TEB
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PVOID \fBStackBase\fP"
.br
.ti -1c
.RI "PVOID \fBStackLimit\fP"
.br
.ti -1c
.RI "PVOID \fBStackAllocationBase\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB264\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "PVOID _INITIAL_TEB::StackAllocationBase"

.PP
Definition at line \fB268\fP of file \fBnosa\&.h\fP\&.
.SS "PVOID _INITIAL_TEB::StackBase"

.PP
Definition at line \fB266\fP of file \fBnosa\&.h\fP\&.
.SS "PVOID _INITIAL_TEB::StackLimit"

.PP
Definition at line \fB267\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
