.TH "_IO_STATUS_BLOCK" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_IO_STATUS_BLOCK
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   NTSTATUS \fBStatus\fP"
.br
.ti -1c
.RI "   PVOID \fBPointer\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "ULONG_PTR \fBInformation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB236\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "union  { \&.\&.\&. }  \fB_IO_STATUS_BLOCK\fP"

.SS "ULONG_PTR _IO_STATUS_BLOCK::Information"

.PP
Definition at line \fB244\fP of file \fBnosa\&.h\fP\&.
.SS "PVOID _IO_STATUS_BLOCK::Pointer"

.PP
Definition at line \fB241\fP of file \fBnosa\&.h\fP\&.
.SS "NTSTATUS _IO_STATUS_BLOCK::Status"

.PP
Definition at line \fB240\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
