.TH "_OBJECT_ATTRIBUTES" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_OBJECT_ATTRIBUTES
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ULONG \fBLength\fP"
.br
.ti -1c
.RI "HANDLE \fBRootDirectory\fP"
.br
.ti -1c
.RI "\fBPUNICODE_STRING\fP \fBObjectName\fP"
.br
.ti -1c
.RI "ULONG \fBAttributes\fP"
.br
.ti -1c
.RI "PVOID \fBSecurityDescriptor\fP"
.br
.ti -1c
.RI "PVOID \fBSecurityQualityOfService\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB254\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG _OBJECT_ATTRIBUTES::Attributes"

.PP
Definition at line \fB259\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _OBJECT_ATTRIBUTES::Length"

.PP
Definition at line \fB256\fP of file \fBnosa\&.h\fP\&.
.SS "\fBPUNICODE_STRING\fP _OBJECT_ATTRIBUTES::ObjectName"

.PP
Definition at line \fB258\fP of file \fBnosa\&.h\fP\&.
.SS "HANDLE _OBJECT_ATTRIBUTES::RootDirectory"

.PP
Definition at line \fB257\fP of file \fBnosa\&.h\fP\&.
.SS "PVOID _OBJECT_ATTRIBUTES::SecurityDescriptor"

.PP
Definition at line \fB260\fP of file \fBnosa\&.h\fP\&.
.SS "PVOID _OBJECT_ATTRIBUTES::SecurityQualityOfService"

.PP
Definition at line \fB261\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
