.TH "_SOCKET_CONTEXT" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SOCKET_CONTEXT
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSOCK_SHARED_INFO\fP \fBSharedData\fP"
.br
.ti -1c
.RI "GUID \fBGuid\fP"
.br
.ti -1c
.RI "ULONG \fBSizeOfHelperData\fP"
.br
.ti -1c
.RI "ULONG \fBPadding\fP"
.br
.ti -1c
.RI "SOCKADDR \fBLocalAddress\fP"
.br
.ti -1c
.RI "SOCKADDR \fBRemoteAddress\fP"
.br
.ti -1c
.RI "PVOID \fBHelper\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing AFD (Ancillary Function Driver) current socket-context informations\&. 
.PP
Definition at line \fB403\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GUID _SOCKET_CONTEXT::Guid"

.PP
Definition at line \fB405\fP of file \fBnosa\&.h\fP\&.
.SS "PVOID _SOCKET_CONTEXT::Helper"

.PP
Definition at line \fB410\fP of file \fBnosa\&.h\fP\&.
.SS "SOCKADDR _SOCKET_CONTEXT::LocalAddress"

.PP
Definition at line \fB408\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _SOCKET_CONTEXT::Padding"

.PP
Definition at line \fB407\fP of file \fBnosa\&.h\fP\&.
.SS "SOCKADDR _SOCKET_CONTEXT::RemoteAddress"

.PP
Definition at line \fB409\fP of file \fBnosa\&.h\fP\&.
.SS "\fBSOCK_SHARED_INFO\fP _SOCKET_CONTEXT::SharedData"

.PP
Definition at line \fB404\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _SOCKET_CONTEXT::SizeOfHelperData"

.PP
Definition at line \fB406\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
