.TH "_SOCK_SHARED_INFO" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SOCK_SHARED_INFO
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSOCKET_STATE\fP \fBState\fP"
.br
.ti -1c
.RI "INT \fBAddressFamily\fP"
.br
.ti -1c
.RI "INT \fBSocketType\fP"
.br
.ti -1c
.RI "INT \fBProtocol\fP"
.br
.ti -1c
.RI "INT \fBSizeOfLocalAddress\fP"
.br
.ti -1c
.RI "INT \fBSizeOfRemoteAddress\fP"
.br
.ti -1c
.RI "struct linger \fBLingerData\fP"
.br
.ti -1c
.RI "ULONG \fBSendTimeout\fP"
.br
.ti -1c
.RI "ULONG \fBRecvTimeout\fP"
.br
.ti -1c
.RI "ULONG \fBSizeOfRecvBuffer\fP"
.br
.ti -1c
.RI "ULONG \fBSizeOfSendBuffer\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   BOOLEAN \fBListening\fP: 1"
.br
.ti -1c
.RI "   BOOLEAN \fBBroadcast\fP: 1"
.br
.ti -1c
.RI "   BOOLEAN \fBDebug\fP: 1"
.br
.ti -1c
.RI "   BOOLEAN \fBOobInline\fP: 1"
.br
.ti -1c
.RI "   BOOLEAN \fBReuseAddresses\fP: 1"
.br
.ti -1c
.RI "   BOOLEAN \fBExclusiveAddressUse\fP: 1"
.br
.ti -1c
.RI "   BOOLEAN \fBNonBlocking\fP: 1"
.br
.ti -1c
.RI "   BOOLEAN \fBDontUseWildcard\fP: 1"
.br
.ti -1c
.RI "   BOOLEAN \fBReceiveShutdown\fP: 1"
.br
.ti -1c
.RI "   BOOLEAN \fBSendShutdown\fP: 1"
.br
.ti -1c
.RI "   BOOLEAN \fBUseDelayedAcceptance\fP: 1"
.br
.ti -1c
.RI "   BOOLEAN \fBUseSAN\fP: 1"
.br
.ti -1c
.RI "   BOOLEAN \fBHasGUID\fP: 1"
.br
.ti -1c
.RI "} \fBFlags\fP"
.br
.ti -1c
.RI "DWORD \fBCreateFlags\fP"
.br
.ti -1c
.RI "DWORD \fBCatalogEntryId\fP"
.br
.ti -1c
.RI "DWORD \fBServiceFlags1\fP"
.br
.ti -1c
.RI "DWORD \fBProviderFlags\fP"
.br
.ti -1c
.RI "DWORD \fBGroupID\fP"
.br
.ti -1c
.RI "DWORD \fBGroupType\fP"
.br
.ti -1c
.RI "INT \fBGroupPriority\fP"
.br
.ti -1c
.RI "INT \fBSocketLastError\fP"
.br
.ti -1c
.RI "HWND \fBhWnd\fP"
.br
.ti -1c
.RI "LONG \fBPadding\fP"
.br
.ti -1c
.RI "DWORD \fBSequenceNumber\fP"
.br
.ti -1c
.RI "UINT \fBwMsg\fP"
.br
.ti -1c
.RI "LONG \fBAsyncEvents\fP"
.br
.ti -1c
.RI "LONG \fBAsyncDisabledEvents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing AFD (Ancillary Function Driver) shared informations\&. 
.PP
Definition at line \fB355\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "INT _SOCK_SHARED_INFO::AddressFamily"

.PP
Definition at line \fB357\fP of file \fBnosa\&.h\fP\&.
.SS "LONG _SOCK_SHARED_INFO::AsyncDisabledEvents"

.PP
Definition at line \fB397\fP of file \fBnosa\&.h\fP\&.
.SS "LONG _SOCK_SHARED_INFO::AsyncEvents"

.PP
Definition at line \fB396\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::Broadcast"

.PP
Definition at line \fB369\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _SOCK_SHARED_INFO::CatalogEntryId"

.PP
Definition at line \fB383\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _SOCK_SHARED_INFO::CreateFlags"

.PP
Definition at line \fB382\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::Debug"

.PP
Definition at line \fB370\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::DontUseWildcard"

.PP
Definition at line \fB375\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::ExclusiveAddressUse"

.PP
Definition at line \fB373\fP of file \fBnosa\&.h\fP\&.
.SS "struct  { \&.\&.\&. }  _SOCK_SHARED_INFO::Flags"

.SS "DWORD _SOCK_SHARED_INFO::GroupID"

.PP
Definition at line \fB386\fP of file \fBnosa\&.h\fP\&.
.SS "INT _SOCK_SHARED_INFO::GroupPriority"

.PP
Definition at line \fB388\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _SOCK_SHARED_INFO::GroupType"

.PP
Definition at line \fB387\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::HasGUID"

.PP
Definition at line \fB380\fP of file \fBnosa\&.h\fP\&.
.SS "HWND _SOCK_SHARED_INFO::hWnd"

.PP
Definition at line \fB390\fP of file \fBnosa\&.h\fP\&.
.SS "struct linger _SOCK_SHARED_INFO::LingerData"

.PP
Definition at line \fB362\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::Listening"

.PP
Definition at line \fB368\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::NonBlocking"

.PP
Definition at line \fB374\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::OobInline"

.PP
Definition at line \fB371\fP of file \fBnosa\&.h\fP\&.
.SS "LONG _SOCK_SHARED_INFO::Padding"

.PP
Definition at line \fB392\fP of file \fBnosa\&.h\fP\&.
.SS "INT _SOCK_SHARED_INFO::Protocol"

.PP
Definition at line \fB359\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _SOCK_SHARED_INFO::ProviderFlags"

.PP
Definition at line \fB385\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::ReceiveShutdown"

.PP
Definition at line \fB376\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _SOCK_SHARED_INFO::RecvTimeout"

.PP
Definition at line \fB364\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::ReuseAddresses"

.PP
Definition at line \fB372\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::SendShutdown"

.PP
Definition at line \fB377\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _SOCK_SHARED_INFO::SendTimeout"

.PP
Definition at line \fB363\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _SOCK_SHARED_INFO::SequenceNumber"

.PP
Definition at line \fB394\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _SOCK_SHARED_INFO::ServiceFlags1"

.PP
Definition at line \fB384\fP of file \fBnosa\&.h\fP\&.
.SS "INT _SOCK_SHARED_INFO::SizeOfLocalAddress"

.PP
Definition at line \fB360\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _SOCK_SHARED_INFO::SizeOfRecvBuffer"

.PP
Definition at line \fB365\fP of file \fBnosa\&.h\fP\&.
.SS "INT _SOCK_SHARED_INFO::SizeOfRemoteAddress"

.PP
Definition at line \fB361\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _SOCK_SHARED_INFO::SizeOfSendBuffer"

.PP
Definition at line \fB366\fP of file \fBnosa\&.h\fP\&.
.SS "INT _SOCK_SHARED_INFO::SocketLastError"

.PP
Definition at line \fB389\fP of file \fBnosa\&.h\fP\&.
.SS "INT _SOCK_SHARED_INFO::SocketType"

.PP
Definition at line \fB358\fP of file \fBnosa\&.h\fP\&.
.SS "\fBSOCKET_STATE\fP _SOCK_SHARED_INFO::State"

.PP
Definition at line \fB356\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::UseDelayedAcceptance"

.PP
Definition at line \fB378\fP of file \fBnosa\&.h\fP\&.
.SS "BOOLEAN _SOCK_SHARED_INFO::UseSAN"

.PP
Definition at line \fB379\fP of file \fBnosa\&.h\fP\&.
.SS "UINT _SOCK_SHARED_INFO::wMsg"

.PP
Definition at line \fB395\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
