.TH "_SOCKADDR_STORAGE" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SOCKADDR_STORAGE
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBss_family\fP"
.br
.ti -1c
.RI "char \fB__ss_pad1\fP [6]"
.br
.ti -1c
.RI "__int64 \fB__ss_align\fP"
.br
.ti -1c
.RI "char \fB__ss_pad2\fP [112]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB332\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "__int64 _SOCKADDR_STORAGE::__ss_align"

.PP
Definition at line \fB335\fP of file \fBnosa\&.h\fP\&.
.SS "char _SOCKADDR_STORAGE::__ss_pad1[6]"

.PP
Definition at line \fB334\fP of file \fBnosa\&.h\fP\&.
.SS "char _SOCKADDR_STORAGE::__ss_pad2[112]"

.PP
Definition at line \fB336\fP of file \fBnosa\&.h\fP\&.
.SS "short _SOCKADDR_STORAGE::ss_family"

.PP
Definition at line \fB333\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
