.TH "_SYSTEM_HANDLE_TABLE_ENTRY_INFO" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SYSTEM_HANDLE_TABLE_ENTRY_INFO
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "USHORT \fBUniqueProcessId\fP"
.br
.ti -1c
.RI "USHORT \fBCreatorBackTraceIndex\fP"
.br
.ti -1c
.RI "UCHAR \fBObjectTypeIndex\fP"
.br
.ti -1c
.RI "UCHAR \fBHandleAttributes\fP"
.br
.ti -1c
.RI "USHORT \fBHandleValue\fP"
.br
.ti -1c
.RI "PVOID \fBObject\fP"
.br
.ti -1c
.RI "ULONG \fBGrantedAccess\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB207\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "USHORT _SYSTEM_HANDLE_TABLE_ENTRY_INFO::CreatorBackTraceIndex"

.PP
Definition at line \fB210\fP of file \fBnosa\&.h\fP\&.
.SS "ULONG _SYSTEM_HANDLE_TABLE_ENTRY_INFO::GrantedAccess"

.PP
Definition at line \fB215\fP of file \fBnosa\&.h\fP\&.
.SS "UCHAR _SYSTEM_HANDLE_TABLE_ENTRY_INFO::HandleAttributes"

.PP
Definition at line \fB212\fP of file \fBnosa\&.h\fP\&.
.SS "USHORT _SYSTEM_HANDLE_TABLE_ENTRY_INFO::HandleValue"

.PP
Definition at line \fB213\fP of file \fBnosa\&.h\fP\&.
.SS "PVOID _SYSTEM_HANDLE_TABLE_ENTRY_INFO::Object"

.PP
Definition at line \fB214\fP of file \fBnosa\&.h\fP\&.
.SS "UCHAR _SYSTEM_HANDLE_TABLE_ENTRY_INFO::ObjectTypeIndex"

.PP
Definition at line \fB211\fP of file \fBnosa\&.h\fP\&.
.SS "USHORT _SYSTEM_HANDLE_TABLE_ENTRY_INFO::UniqueProcessId"

.PP
Definition at line \fB209\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
