.TH "_WSAPROTOCOL_INFOW" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_WSAPROTOCOL_INFOW
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nosa\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBdwServiceFlags1\fP"
.br
.ti -1c
.RI "DWORD \fBdwServiceFlags2\fP"
.br
.ti -1c
.RI "DWORD \fBdwServiceFlags3\fP"
.br
.ti -1c
.RI "DWORD \fBdwServiceFlags4\fP"
.br
.ti -1c
.RI "DWORD \fBdwProviderFlags\fP"
.br
.ti -1c
.RI "GUID \fBProviderId\fP"
.br
.ti -1c
.RI "DWORD \fBdwCatalogEntryId\fP"
.br
.ti -1c
.RI "\fBWSAPROTOCOLCHAIN\fP \fBProtocolChain\fP"
.br
.ti -1c
.RI "int \fBiVersion\fP"
.br
.ti -1c
.RI "int \fBiAddressFamily\fP"
.br
.ti -1c
.RI "int \fBiMaxSockAddr\fP"
.br
.ti -1c
.RI "int \fBiMinSockAddr\fP"
.br
.ti -1c
.RI "int \fBiSocketType\fP"
.br
.ti -1c
.RI "int \fBiProtocol\fP"
.br
.ti -1c
.RI "int \fBiProtocolMaxOffset\fP"
.br
.ti -1c
.RI "int \fBiNetworkByteOrder\fP"
.br
.ti -1c
.RI "int \fBiSecurityScheme\fP"
.br
.ti -1c
.RI "DWORD \fBdwMessageSize\fP"
.br
.ti -1c
.RI "DWORD \fBdwProviderReserved\fP"
.br
.ti -1c
.RI "WCHAR \fBszProtocol\fP [\fBWSAPROTOCOL_LEN\fP+1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB183\fP of file \fBnosa\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "DWORD _WSAPROTOCOL_INFOW::dwCatalogEntryId"

.PP
Definition at line \fB191\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _WSAPROTOCOL_INFOW::dwMessageSize"

.PP
Definition at line \fB202\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _WSAPROTOCOL_INFOW::dwProviderFlags"

.PP
Definition at line \fB189\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _WSAPROTOCOL_INFOW::dwProviderReserved"

.PP
Definition at line \fB203\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _WSAPROTOCOL_INFOW::dwServiceFlags1"

.PP
Definition at line \fB185\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _WSAPROTOCOL_INFOW::dwServiceFlags2"

.PP
Definition at line \fB186\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _WSAPROTOCOL_INFOW::dwServiceFlags3"

.PP
Definition at line \fB187\fP of file \fBnosa\&.h\fP\&.
.SS "DWORD _WSAPROTOCOL_INFOW::dwServiceFlags4"

.PP
Definition at line \fB188\fP of file \fBnosa\&.h\fP\&.
.SS "int _WSAPROTOCOL_INFOW::iAddressFamily"

.PP
Definition at line \fB194\fP of file \fBnosa\&.h\fP\&.
.SS "int _WSAPROTOCOL_INFOW::iMaxSockAddr"

.PP
Definition at line \fB195\fP of file \fBnosa\&.h\fP\&.
.SS "int _WSAPROTOCOL_INFOW::iMinSockAddr"

.PP
Definition at line \fB196\fP of file \fBnosa\&.h\fP\&.
.SS "int _WSAPROTOCOL_INFOW::iNetworkByteOrder"

.PP
Definition at line \fB200\fP of file \fBnosa\&.h\fP\&.
.SS "int _WSAPROTOCOL_INFOW::iProtocol"

.PP
Definition at line \fB198\fP of file \fBnosa\&.h\fP\&.
.SS "int _WSAPROTOCOL_INFOW::iProtocolMaxOffset"

.PP
Definition at line \fB199\fP of file \fBnosa\&.h\fP\&.
.SS "int _WSAPROTOCOL_INFOW::iSecurityScheme"

.PP
Definition at line \fB201\fP of file \fBnosa\&.h\fP\&.
.SS "int _WSAPROTOCOL_INFOW::iSocketType"

.PP
Definition at line \fB197\fP of file \fBnosa\&.h\fP\&.
.SS "int _WSAPROTOCOL_INFOW::iVersion"

.PP
Definition at line \fB193\fP of file \fBnosa\&.h\fP\&.
.SS "\fBWSAPROTOCOLCHAIN\fP _WSAPROTOCOL_INFOW::ProtocolChain"

.PP
Definition at line \fB192\fP of file \fBnosa\&.h\fP\&.
.SS "GUID _WSAPROTOCOL_INFOW::ProviderId"

.PP
Definition at line \fB190\fP of file \fBnosa\&.h\fP\&.
.SS "WCHAR _WSAPROTOCOL_INFOW::szProtocol[\fBWSAPROTOCOL_LEN\fP+1]"

.PP
Definition at line \fB204\fP of file \fBnosa\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
