.TH "nosa-example.c" 3 "Version 0.0.1" "Lib Nosa (No Socket API)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nosa-example.c
.SH SYNOPSIS
.br
.PP
\fR#include 'nosa\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
Establishes a connection to a specified host and port using a specified socket type\&.

.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturns\fP
.RS 4
0 upon successful execution 
.RE
.PP

.PP
Definition at line \fB10\fP of file \fBnosa\-example\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lib Nosa (No Socket API) from the source code\&.
