var annotated_dup =
[
    [ "_AFD_ACCEPT_DATA", "struct___a_f_d___a_c_c_e_p_t___d_a_t_a.html", "struct___a_f_d___a_c_c_e_p_t___d_a_t_a" ],
    [ "_AFD_BIND_DATA", "struct___a_f_d___b_i_n_d___d_a_t_a.html", "struct___a_f_d___b_i_n_d___d_a_t_a" ],
    [ "_AFD_CONNECT_INFO", "struct___a_f_d___c_o_n_n_e_c_t___i_n_f_o.html", "struct___a_f_d___c_o_n_n_e_c_t___i_n_f_o" ],
    [ "_AFD_CREATE_PACKET", "struct___a_f_d___c_r_e_a_t_e___p_a_c_k_e_t.html", "struct___a_f_d___c_r_e_a_t_e___p_a_c_k_e_t" ],
    [ "_AFD_LISTEN_DATA", "struct___a_f_d___l_i_s_t_e_n___d_a_t_a.html", "struct___a_f_d___l_i_s_t_e_n___d_a_t_a" ],
    [ "_AFD_RECV_INFO", "struct___a_f_d___r_e_c_v___i_n_f_o.html", "struct___a_f_d___r_e_c_v___i_n_f_o" ],
    [ "_AFD_RECV_INFO_UDP", "struct___a_f_d___r_e_c_v___i_n_f_o___u_d_p.html", "struct___a_f_d___r_e_c_v___i_n_f_o___u_d_p" ],
    [ "_AFD_SEND_INFO", "struct___a_f_d___s_e_n_d___i_n_f_o.html", "struct___a_f_d___s_e_n_d___i_n_f_o" ],
    [ "_AFD_SEND_INFO_UDP", "struct___a_f_d___s_e_n_d___i_n_f_o___u_d_p.html", "struct___a_f_d___s_e_n_d___i_n_f_o___u_d_p" ],
    [ "_AFD_WSABUF", "struct___a_f_d___w_s_a_b_u_f.html", "struct___a_f_d___w_s_a_b_u_f" ],
    [ "_CLIENT_ID", "struct___c_l_i_e_n_t___i_d.html", "struct___c_l_i_e_n_t___i_d" ],
    [ "_DOMAIN_INFO", "struct___d_o_m_a_i_n___i_n_f_o.html", "struct___d_o_m_a_i_n___i_n_f_o" ],
    [ "_INITIAL_TEB", "struct___i_n_i_t_i_a_l___t_e_b.html", "struct___i_n_i_t_i_a_l___t_e_b" ],
    [ "_IO_STATUS_BLOCK", "struct___i_o___s_t_a_t_u_s___b_l_o_c_k.html", "struct___i_o___s_t_a_t_u_s___b_l_o_c_k" ],
    [ "_OBJECT_ATTRIBUTES", "struct___o_b_j_e_c_t___a_t_t_r_i_b_u_t_e_s.html", "struct___o_b_j_e_c_t___a_t_t_r_i_b_u_t_e_s" ],
    [ "_SOCK_SHARED_INFO", "struct___s_o_c_k___s_h_a_r_e_d___i_n_f_o.html", "struct___s_o_c_k___s_h_a_r_e_d___i_n_f_o" ],
    [ "_SOCKADDR_STORAGE", "struct___s_o_c_k_a_d_d_r___s_t_o_r_a_g_e.html", "struct___s_o_c_k_a_d_d_r___s_t_o_r_a_g_e" ],
    [ "_SOCKET_CONTEXT", "struct___s_o_c_k_e_t___c_o_n_t_e_x_t.html", "struct___s_o_c_k_e_t___c_o_n_t_e_x_t" ],
    [ "_SYSTEM_HANDLE_INFORMATION", "struct___s_y_s_t_e_m___h_a_n_d_l_e___i_n_f_o_r_m_a_t_i_o_n.html", "struct___s_y_s_t_e_m___h_a_n_d_l_e___i_n_f_o_r_m_a_t_i_o_n" ],
    [ "_SYSTEM_HANDLE_TABLE_ENTRY_INFO", "struct___s_y_s_t_e_m___h_a_n_d_l_e___t_a_b_l_e___e_n_t_r_y___i_n_f_o.html", "struct___s_y_s_t_e_m___h_a_n_d_l_e___t_a_b_l_e___e_n_t_r_y___i_n_f_o" ],
    [ "_UNICODE_STRING", "struct___u_n_i_c_o_d_e___s_t_r_i_n_g.html", "struct___u_n_i_c_o_d_e___s_t_r_i_n_g" ],
    [ "_WSAPROTOCOL_INFOW", "struct___w_s_a_p_r_o_t_o_c_o_l___i_n_f_o_w.html", "struct___w_s_a_p_r_o_t_o_c_o_l___i_n_f_o_w" ],
    [ "_WSAPROTOCOLCHAIN", "struct___w_s_a_p_r_o_t_o_c_o_l_c_h_a_i_n.html", "struct___w_s_a_p_r_o_t_o_c_o_l_c_h_a_i_n" ],
    [ "buffer_data_t", "structbuffer__data__t.html", "structbuffer__data__t" ],
    [ "userbuf_t", "structuserbuf__t.html", "structuserbuf__t" ]
];